### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lianfeng30** [reconned/domained#1]
hi.

i'm install error  。。  i used Mac pro

here:
Installing massdns
Cloning into './bin/massdns'...
remote: Counting objects: 356, done.
remote: Total 356 (delta 0), reused 0 (delta 0), pack-reused 356
Receiving objects: 100% (356/356), 562.68 KiB | 165.00 KiB/s, done.
Resolving deltas: 100% (208/208), done.
mkdir -p bin
cc  -std=c11 -Wall -fstack-protector-strong *.c -o bin/massdns -lldns -ldl
main.c:15:10: fatal error: 'ldns/rbtree.h' file not found
#include <ldns/rbtree.h>
         ^
1 error generated.
make: *** [all] Error 1

i'm ldns:
ldns-version
1.7.0
$ which ldnsd
/usr/local/bin/ldnsd

There is a problem, I installed ldns, suggested a openssl error
Will it be for this reason?

Looking forward to your reply, thank you

**Comment by lianfeng30** [comment]
ldns-1.7.0$
configure: error: OpenSSL found in /usr/local/ssl, but version 0.9.7 or higher is required

**Comment by lianfeng30** [comment]
$ OpenSSL version
OpenSSL 1.0.2l  25 May 2017

**Comment by OrOneEqualsOne** [comment]
Lianfeng30, thanks for your support. What operating system are you using? Are you using Kali Linux or Debian 7+?

**Comment by lianfeng30** [comment]
i used Mac pro

**Comment by lianfeng30** [comment]
thanks
